#ifndef COLORS_H
#define COLORS_h

#define DEFAULT_COLOR_DOT "black"
#define RED_COLOR_DOT     "#FF0000"
#define BLUE_BG_COLOR_DOT "#9CC4FF"
#define RED_BG_COLOR_DOT  "#FC9696"
#define BLUE_COLOR_DOT    "#4C6CEC"
#define GREEN_COLOR_DOT   "#69EF69"
#define ORANGE_COLOR_DOT  "#FC9F42"
#define GRAY_COLOR_DOT    "#B6B6B6"
#define HEAD_NODE_COLOR   "#C295FD"
#define TAIL_NODE_COLOR   "#F3A32B"
#define FREE_NODE_COLOR   "#3BD473"
#define ORAN_BG_COLOR_DOT "#FAAC71"
#define PURP_BG_COLOR_DOT "#9370DB"

#endif
